In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("IMDB Dataset.csv")
df.head(10)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [4]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

Lowercase

In [7]:
df['review'] = df['review'].str.lower()

In [8]:
df.head(10)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive
5  probably my all-time favorite movie, a story o...  positive
6  i sure would like to see a resurrection of a u...  positive
7  this show was an amazing, fresh & innovative i...  negative
8  encouraged by the positive comments about this...  negative
9  if you like original gut wrenching laughter yo...  positive

Remove HTML Tags

In [9]:
import re

In [11]:
def stripHTML(data):
     p = re.compile('<.+?>')
     return p.sub(r'',data)

In [12]:
print(stripHTML("<ak>hfiwf</a>"))

hfiwf

In [13]:
df['review'] = df['review'].apply(stripHTML)

In [15]:
df.head(10)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive
5  probably my all-time favorite movie, a story o...  positive
6  i sure would like to see a resurrection of a u...  positive
7  this show was an amazing, fresh & innovative i...  negative
8  encouraged by the positive comments about this...  negative
9  if you like original gut wrenching laughter yo...  positive

Remove URL

In [18]:
text1 = "check out https://www.kaggle.com/code/campusx/text-preprocessing/output"

In [19]:
def remove_URL(text):
     pattern = re.compile(r'https?://\S+|www\.\S+')
     return pattern.sub(r'', text)

In [20]:
print(remove_URL(text1))

check out

In [21]:
df['review'] = df['review'].apply(remove_URL)

Removing Punctuation

In [97]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [98]:
exclude = string.punctuation

In [99]:
def remove_PUNCTUATION(text):
     no_punctuation_text = ''.join(char for char in text if char not in string.punctuation)
     return no_punctuation_text

In [100]:
text2 = "String. with. python?"

In [101]:
start = time.time()
print(remove_PUNCTUATION(text2))
time1 = time.time() - start
print(time1*50000)

String with python
0.0

In [102]:
def remove_PUNCTUATION_faster(text):
     return text.translate(str.maketrans('','',exclude))

In [103]:
start = time.time()
print(remove_PUNCTUATION_faster(text2))
time2 = time.time() - start
print(time2*50000)

String with python
0.0

In [104]:
df['review'] = df['review'].apply(remove_PUNCTUATION_faster)

In [105]:
df.head(10)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive
5  probably my alltime favorite movie a story of ...  positive
6  i sure would like to see a resurrection of a u...  positive
7  this show was an amazing fresh  innovative ide...  negative
8  encouraged by the positive comments about this...  negative
9  if you like original gut wrenching laughter yo...  positive

Chat Word Treatment

In [106]:
# AFAIK=As Far As I Know
# AFK=Away From Keyboard
# ASAP=As Soon As Possible
# ATK=At The Keyboard
# ATM=At The Moment
# A3=Anytime, Anywhere, Anyplace
# BAK=Back At Keyboard
# BBL=Be Back Later
# BBS=Be Back Soon
# BFN=Bye For Now
# B4N=Bye For Now
# BRB=Be Right Back
# BRT=Be Right There
# BTW=By The Way
# B4=Before
# B4N=Bye For Now
# CU=See You
# CUL8R=See You Later
# CYA=See You
# FAQ=Frequently Asked Questions
# FC=Fingers Crossed
# FWIW=For What It's Worth
# FYI=For Your Information
# GAL=Get A Life
# GG=Good Game
# GN=Good Night
# GMTA=Great Minds Think Alike
# GR8=Great!
# G9=Genius
# IC=I See
# ICQ=I Seek you (also a chat program)
# ILU=ILU: I Love You
# IMHO=In My Honest/Humble Opinion
# IMO=In My Opinion
# IOW=In Other Words
# IRL=In Real Life
# KISS=Keep It Simple, Stupid
# LDR=Long Distance Relationship
# LMAO=Laugh My A.. Off
# LOL=Laughing Out Loud
# LTNS=Long Time No See
# L8R=Later
# MTE=My Thoughts Exactly
# M8=Mate
# NRN=No Reply Necessary
# OIC=Oh I See
# PITA=Pain In The A..
# PRT=Party
# PRW=Parents Are Watching
# QPSA?	Que Pasa?
# ROFL=Rolling On The Floor Laughing
# ROFLOL=Rolling On The Floor Laughing Out Loud
# ROTFLMAO=Rolling On The Floor Laughing My A.. Off
# SK8=Skate
# STATS=Your sex and age
# ASL=Age, Sex, Location
# THX=Thank You
# TTFN=Ta-Ta For Now!
# TTYL=Talk To You Later
# U=You
# U2=You Too
# U4E=Yours For Ever
# WB=Welcome Back
# WTF=What The F...
# WTG=Way To Go!
# WUF=Where Are You From?
# W8=Wait...
# 7K=Sick:-D Laugher
# TFW – That feeling when. TFW internet slang often goes in a caption to an image.
# MFW – My face when
# MRW – My reaction when
# IFYP – I feel your pain
# LOL – Laughing out loud
# TNTL – Trying not to laugh
# JK – Just kidding
# IDC – I don’t care
# ILY – I love you
# IMU – I miss you
# ADIH – Another day in hell
# IDC – I don’t care
# ZZZ – Sleeping, bored, tired
# WYWH – Wish you were here
# TIME – Tears in my eyes
# BAE – Before anyone else
# FIMH – Forever in my heart
# BSAAW – Big smile and a wink
# BWL – Bursting with laughter
# LMAO – Laughing my a** off
# BFF: Best friends forever
# CSL – Can’t stop laughing

In [111]:
chat_words = {'U':'You'}  #the dictionary
def chat_conversion(text):
     new_text = []
     for w in text.split():
          if w.upper() in chat_words:
               new_text.append(chat_words[w.upper()])
          else:
               new_text.append(w)
     return " ".join(new_text)

In [112]:
print(chat_conversion("u r good"))

You r good

Spelling Mistake

In [116]:
from textblob import TextBlob

In [118]:
incorrect_text = "Ceertain conditions duriing seveal ggenerations aree modified srry"

txtBlb = TextBlob(incorrect_text)

textblb = txtBlb.correct()

In [119]:
print(textblb)

Certain conditions during several generations are modified sorry

Removing Stop Words

In [127]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

True

In [129]:
from nltk.corpus import stopwords

In [130]:
def remove_STOPWORDS(text):
     new_txt = []
     for word in text.split():
          if word in stopwords.words('english'):
               new_txt.append('')
          else:
               new_txt.append(word)
     x = new_txt[:]
     new_txt.clear()
     return " ".join(x)

In [131]:
print(remove_STOPWORDS("probly my all-time fav a story"))

probly  all-time fav  story

Handling Emojis

In [132]:
import emoji
print(emoji.demojize('python is 🔥'))

python is :fire:

Tokenization